### ISSUE TITLE
error running rake db:migrate on a new install

### ISSUE THREAD

**Issue by dchelimsky** [mwerbos/Choron#47]
```
$ ruby --version
ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-darwin13.0.2]
$ git clone https://github.com/tigrennatenn/Choron.git
$ cd Choron
$ bundle install
# ....
$ rake db:create
$ rake db:migrate
rake aborted!
Could not find table 'settings'
/Users/david/src/Choron/config/initializers/params.rb:2:in `<top (required)>'
/Users/david/src/Choron/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```

**Comment by mwerbos** [comment]
I think this is a known problem. For a hacky way around it, try going to
config/initializers/params.rb, and comment out the two lines involving
Setting.

**Comment by mwerbos** [comment]
Basically the issue is that those settings are checked on server startup -
but also when you run the migration - so when you try to do the migration,
it looks for a table you don't have yet. If you comment those lines, run
the migration, then uncomment them again, it should be fine.

We should probably look for a less dank solution at some point though.

(By the way, I'm Maia, and I don't know who you are. How did you happen
upon Choron?)

**Comment by dchelimsky** [comment]
@ozymandiasthegreat's and I are cousins and he mentioned Choron. Given my own history w/ Ruby and Ruby on Rails and my lack of ability to manage household chores, I figured I'd check it out :)

**Comment by dchelimsky** [comment]
I submitted PR #48 that gets past the `Settings` issue, but exposes a new one:

```
 rake db:migrate
==  CreateUsers: migrating ====================================================
-- add_column(:users, :chorons, :integer)
rake aborted!
An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: no such table: users: ALTER TABLE "users" ADD "chorons" integer/Users/david/src/Choron/db/migrate/20120902070422_create_users.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by dchelimsky** [comment]
The first migration is 20120902070422_create_users.rb, which doesn't create users, it alters the table (which doesn't exist yet). I started to fix this by making it create the table instead, but then ran into a similar issue:

```
SQLite3::SQLException: no such table: users: ALTER TABLE "users" ADD "chorons" integer/Users/david/src/Choron/db/migrate/20120902070422_create_users.rb:3:in `
change'
```

So it seems as though there is something broken in how you're using Rails migrations.

I was able to bootstrap the db using `rake db:schema:load`, so I added another commit to the PR that removes all of the existing migrations and replaces them with a single migration based on db/schema.rb. That solves this issue i.e. you can bootstrap using `rake db:migrate`, but it means you can't roll back to any previous versions of the schema and you still have a process problem to figure out (using Rails migrations properly).

Hope this helps.

**Comment by dchelimsky** [comment]
Well - that PR might not help :) I was able to run the migration successfully but now the integration tests fail and I can't run the app :(

That's all I've got time for now, but I'd recommend that you create a new install of the app yourself and work your way through these issues if you want other people to be able to use the app. Don't worry about it if you don't care about that.

**Comment by ozziefallick** [comment]
Thanks for exposing the problems and giving it a shot! We're probably not going to be focused on making Choron painlessly shippable until the summer, but we'll definitely try to iron this stuff out then.

**Comment by dchelimsky** [comment]
My pleasure. Please comment on this issue if/when these things get resolved so I get notified. I'll look forward to checking it out in the summer, and in the mean time I guess the floors will just have to unswept and the windows covered with dust ;)
